### ISSUE TITLE
Lacking a seperator in the end?

### ISSUE THREAD

**Issue by dequeueing** [LMCache/lmcache-vllm#32]
Hi. I suspect that we should add another separator at the end of the input. Otherwise if the last chunk is computed already, it may not be recognized so cannot reuse its KV cache. 

https://github.com/LMCache/lmcache-vllm/blob/b890544e7efbaa2738902889c6f4ac56cc22ecd5/lmcache_vllm/blend_adapter.py#L80-L93

**Comment by ApostaC** [comment]
Hey @dequeueing , the last chunk doesn't need to be appended with the separator. The LMCache can still retrieve the "matching part" because it's a prefix.

For example, if the computed chunk is [a, b, c, d, e, x] and the query is [a, b, c, d, e], LMCache can still retrieve the KV cache of [a, b, c, d, e].

Btw, we are developing some new functionalities to run the blend without special tokens. Please see #33 and LMCache/LMCache#209
